apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment

spec:
  selector:
    matchLabels:
      app: node-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: node-deployment
    spec:
      containers:
        - name: node-container
          image: ECR_IMG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1 
kind: Service
metadata: 
  name: node-service
spec:
  type: NodePort
  selector:
    app: node-deployment
  ports:
    - port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
      protocol: TCP
      nodePort: 32000  
  